global:
  resolve_timeout: 1m

route:
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1m
  receiver: webhook

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://localhost:5001/'

